name: Run playbook

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

uses: dawidd6/action-ansible-playbook@v2
with:
  # Required, playbook filepath
  playbook: ansible/ec2_deploy.yml
  # Optional, directory where playbooks live
  directory: ./
  # Optional, SSH private key
  key: ${{secrets.WORKFLOW_TOKEN}}
  # Optional, literal inventory file contents
  # Optional, SSH known hosts file content
  known_hosts: .known_hosts
  # Optional, encrypted vault password
  vault_password: '123456'
